# Generated by Django 5.0.2 on 2025-01-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_brand_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('None', 'None'), ('New Arrivals', 'New Arrivals'), ('Top Rated', 'Top Rated'), ('Featured', 'Featured')], max_length=25),
        ),
    ]
