# Generated by Django 5.0.2 on 2025-10-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_showroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModularKitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='modular_kitchen/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower number = first)')),
            ],
            options={
                'verbose_name': 'Modular Kitchen',
                'verbose_name_plural': 'Modular Kitchens',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Showroom',
        ),
    ]
