# Generated by Django 5.0.2 on 2025-10-03 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_topproductofweek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topproductofweek',
            name='price',
        ),
    ]
