# Generated by Django 5.0.2 on 2025-10-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
