# Generated by Django 5.0.2 on 2025-10-04 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_specification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specification',
            options={},
        ),
        migrations.AlterField(
            model_name='specification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
