# Generated by Django 5.0.2 on 2025-10-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock'), ('Limited Stock', 'Limited Stock'), ('Pre Order', 'Pre Order')], default='None', max_length=50),
        ),
    ]
