# Generated by Django 5.0.2 on 2025-10-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_product_availability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Availability',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock'), ('Limited Stock', 'Limited Stock'), ('Pre Order', 'Pre Order')], default='In Stock', max_length=50),
        ),
    ]
