# Generated by Django 5.0.2 on 2025-10-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='copy_right',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
