# Generated by Django 5.0.2 on 2025-10-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('chat_status', models.BooleanField(default=True)),
                ('opening_time', models.CharField(default='10:30 AM', max_length=20)),
                ('closing_time', models.CharField(default='10:30 PM', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Support',
                'verbose_name_plural': 'Customer Support',
            },
        ),
    ]
